### ISSUE TITLE
Live plots without checkpoints

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#1256]
Even if `checkpoints` are not enabled on `dvc.yaml`, DVCLive still generates plots that are updated at the end of each training iteration (a.k.a `step`), and the [htm report ](https://dvc.org/doc/dvclive/dvclive-with-dvc#html-report)generated by DVC gets updated.

However, without `checkpoints` the vscode-dvc extension does not update the live plots because the `exp show` output does not reflect this updates. 

Simple project to test:

```yaml
stages:
  test-dvclive:
    cmd: python test_dvclive.py
    live:
      dvclive:
        cache: false
        summary: true
        html: true
```

```python
import random
import time

from dvclive import Live


live = Live()

for i in range(10):
    live.log("foo", i + random.random())
    live.log("bar", i + random.random())
    time.sleep(5)
    live.next_step()
```

`dvc repro`/`dvc exp run` and open `dvclive_dvc_plots/index.html`.
