### ISSUE TITLE
Broken yaml hierarchy in the default output

### ISSUE THREAD

**Issue by tibor-mach** [iterative/vscode-dvc#2390]
cc @shcheklein 
Continuing the discussion on [Discord](https://discord.com/channels/485586884165107732/1018917508746588192) 

Hierarchy of parameters seems to be split into multiple columns in the VS code extension.

A simple example where this can be reproduced:
https://github.com/tibor-mach/vscodedvc-example

**Comment by daavoo** [comment]
Was about to report similar.

This is the simplest structure I have found that triggers the bug:

```yaml
one:
  two:
    three: 
      works: true
      four: 
        breaks: true
```
