### ISSUE TITLE
`Run Experiment` setup generates an ivalid `dvc.yaml` when not using `File explorer`.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#3685]
When trying to use the `Run Experiment` button and following the setup of a new stage, the resulting stage contains some weird relative paths.

This only occurs if I just write the name of the script instead of using the `File explorer`:

https://user-images.githubusercontent.com/12677733/231997467-dc72f1dc-038e-49db-8856-944c81cd49d6.mov

---

Writing `train.py`:

```yaml

# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  train:
    cmd: python ../../../../../train.py
    deps:
      - ../../../../../train.py
```

Using `File explorer`:

```yaml
# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
```
