### ISSUE TITLE
Improve `dvc.yaml` generation

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#4194]
### Current
**UI:**

<img width="404" alt="image" src="https://github.com/iterative/vscode-dvc/assets/43496356/9f9fb881-c502-4eab-8e9a-d7e2f5a6be9d">

**Generated `dvc.yaml` or update to already created file:**

```

# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  train:
    cmd: python requirements.txt
    deps:
      - requirements.txt
```

### Improvements

- [x] Try alternative phrasing in place of "pipeline" for more clarity. Referring to it as`dvc.yaml` for example. 
- [x] Expand UI text a bit more, giving a more full explanation on what pressing the button will do for the user
- [x] Add more comments to `dvc.yaml`, giving a more in-depth explanation of `dvc.yaml` with some configuration examples 

Related #3331
