### ISSUE TITLE
Different `train` stage `metrics` and `params` paths relative to Git repo root

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4526]
I just had a long running queued experiment finish. The results of it are shown in the Experiments table. However, the paths of the `params.yaml` and `metrics.json` file have changed and are different for previously run experiments and this latest one. I haven't changed my `dvc.yaml` file. I have updated my DVC VS Code Extension today, however.

<img width="618" alt="Screen Shot 2023-08-17 at 8 58 42 PM" src="https://github.com/iterative/vscode-dvc/assets/77496589/025566c3-1f8f-4f18-ad43-1a432680e136">

**Comment by julieg18** [comment]
@aschuh-hf, do these unexpected columns appear if you run `dvc exp show` in the terminal?

**Comment by aschuh-hf** [comment]
The `dvc exp show --json` command copied from the "DVC" output View tab shows the same unexpected paths:

```
...
        "experiments": [
            {
                "revs": [
                    {
                        "rev": "437008df5ad6033dd9913edc60104fe7d3b23730",
                        "name": "moldy-sida",
                        "data": {
                            "rev": "437008df5ad6033dd9913edc60104fe7d3b23730",
                            "timestamp": "2023-08-17T17:51:51",
                            "params": {
                                "projects/multiseries/trials/pairwise_selected_target_series/params.yaml": {
...
```

**Comment by julieg18** [comment]
The extension columns is reflecting what DVC is sending. Can you upgrade to the latest version of DVC? If that doesn't fix the issue, we'll open an issue in the DVC repo.

**Comment by aschuh-hf** [comment]
I upgraded to DVC 3.15.2 (latest version on conda-forge).

The `dvc exp show --json` output still contains the full path relative to the Git repository root rather than DVC project root.

I applied the experiment to the workspace using `dvc exp apply moldy-sida` and the `dvc.lock` file contains correct paths:
```
    outs:
    - path: data/train/metrics.json
      hash: md5
      md5: a67e831e04b2a488ab5c58b930576c52
      size: 962
    - path: data/train/plots/metrics
      hash: md5
      md5: c333319f6ae3e1fbea29cc6fe65a8ce4.dir
      size: 453569
      nfiles: 22
```
